const STILLFAILING_array = [

];

const DONOTREDIRECT_array = [
    {reqUrl:'/en/', expStatus:200, expUrl:'/en/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/', expStatus:200, expUrl:'/fr/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/newsstand/', expStatus:200, expUrl:'/en/newsstand/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/kiosque/', expStatus:200, expUrl:'/fr/kiosque/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/pricing/', expStatus:200, expUrl:'/en/pricing/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/newsstand/', expStatus:200, expUrl:'/en/newsstand/', reqNotes:'MUST NOT REDIRECT, possible pll_language cookie issue'},
    {reqUrl:'/en/features/', expStatus:200, expUrl:'/en/features/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/about-us/contact-us/', expStatus:200, expUrl:'/en/about-us/contact-us/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/device-ipad/', expStatus:200, expUrl:'/en/device-ipad/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/device-android/', expStatus:200, expUrl:'/en/device-android/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/device-kindle-fire/', expStatus:200, expUrl:'/en/device-kindle-fire/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/terms-of-service/', expStatus:200, expUrl:'/en/legal/terms-of-service/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/copyright-policy/', expStatus:200, expUrl:'/en/legal/copyright-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/privacy-policy/', expStatus:200, expUrl:'/en/legal/privacy-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/inapp-terms-of-service/', expStatus:200, expUrl:'/en/legal/inapp-terms-of-service/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/inapp-copyright-policy/', expStatus:200, expUrl:'/en/legal/inapp-copyright-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/inapp-rogers-copyright-policy/', expStatus:200, expUrl:'/en/legal/inapp-rogers-copyright-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/inapp-privacy-policy/', expStatus:200, expUrl:'/en/legal/inapp-privacy-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/tarification/', expStatus:200, expUrl:'/fr/tarification/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/kiosque/', expStatus:200, expUrl:'/fr/kiosque/', reqNotes:'MUST NOT REDIRECT, possible pll_language cookie issue'},
    {reqUrl:'/fr/fonctionnalites/', expStatus:200, expUrl:'/fr/fonctionnalites/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/a-propos-de-nous/contactez-nous/', expStatus:200, expUrl:'/fr/a-propos-de-nous/contactez-nous/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/ipad-et-iphone/', expStatus:200, expUrl:'/fr/ipad-et-iphone/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/device-android-fr/', expStatus:200, expUrl:'/fr/device-android-fr/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/kindle-fire/', expStatus:200, expUrl:'/fr/kindle-fire/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/conditions-dutilisation/', expStatus:200, expUrl:'/fr/politiques/conditions-dutilisation/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/inapp-conditions-dutilisation/', expStatus:200, expUrl:'/fr/politiques/inapp-conditions-dutilisation/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/inapp-droit-dauteur/', expStatus:200, expUrl:'/fr/politiques/inapp-droit-dauteur/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/inapp-politique-canadienne-sur-le-droit-dauteur/', expStatus:200, expUrl:'/fr/politiques/inapp-politique-canadienne-sur-le-droit-dauteur/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/inapp-confidentialite/', expStatus:200, expUrl:'/fr/politiques/inapp-confidentialite/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/droit-dauteur/', expStatus:200, expUrl:'/fr/politiques/droit-dauteur/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/confidentialite/', expStatus:200, expUrl:'/fr/politiques/confidentialite/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/support-fr/', expStatus:200, expUrl:'https://support.texture.ca/fr/', reqNotes:'DO NOT CHANGE, CORS'},
    {reqUrl:'/en/support/', expStatus:200, expUrl:'https://support.texture.ca/en/', reqNotes:'DO NOT CHANGE, CORS'},
    {reqUrl:'/blog', expStatus:200, expUrl:'/en/blog/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/en/blog', expStatus:200, expUrl:'/en/blog/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/en/blog/', expStatus:200, expUrl:'/en/blog/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/blogue', expStatus:200, expUrl:'/fr/blogue/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/blogue/', expStatus:200, expUrl:'/fr/blogue/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/fr/blogue', expStatus:200, expUrl:'/fr/blogue/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/fr/blogue/', expStatus:200, expUrl:'/fr/blogue/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/en/dl/category/9000000000041/', expStatus:200, expUrl:'/en/dl/category/9000000000041/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/dl/view/highlights/', expStatus:200, expUrl:'/en/dl/view/highlights/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/magazines/ebony-fr/', expStatus:200, expUrl:'/fr/magazines/ebony-fr/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/magazines/ebony/', expStatus:200, expUrl:'/en/magazines/ebony/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/canadian-favourites-magazines/', expStatus:200, expUrl:'/en/canadian-favourites-magazines/', reqNotes:'Could this redirect?'},
    {reqUrl:'/en/2017/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/2009/12/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/2009/whateverafter', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/2016/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/2005/08/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/2012/whateverafter', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/en/tag', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/tag/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/tag/whatever-you-put-after', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/tag', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/tag/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/tag/whatever-you-put-after', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/en/article', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/article/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/article/whatever-you-put-after', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/article', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/article/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/article/whatever-you-put-after', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/en/?nimportalpartner=delta-airlines', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/?nimportalpartner=delta-airlines-fr', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/magazines/ebony-fr/', expStatus:200, expUrl:'/fr/magazines/ebony-fr/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/magazines/ebony/', expStatus:200, expUrl:'/en/magazines/ebony/', reqNotes:'MUST NOT REDIRECT'}
];


const TAXONOMY_ARRAY = [
    {reqUrl:'/en/canadian-favourites-magazines/', expStatus:200, expUrl:'/en/canadian-favourites-magazines/', reqNotes:'Could this redirect?'},
    {reqUrl:'/en/2017/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/2009/12/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/2009/whateverafter', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/2016/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/2005/08/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/2012/whateverafter', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/en/tag', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/tag/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/tag/whatever-you-put-after', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/tag', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/tag/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/tag/whatever-you-put-after', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/en/article', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/article/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/article/whatever-you-put-after', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/article', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/article/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/article/whatever-you-put-after', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/en/?nimportalpartner=delta-airlines', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/?nimportalpartner=delta-airlines-fr', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/magazines/ebony-fr/', expStatus:200, expUrl:'/fr/magazines/ebony-fr/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/magazines/ebony/', expStatus:200, expUrl:'/en/magazines/ebony/', reqNotes:'MUST NOT REDIRECT'},
];

let A1 = [
    {reqUrl:'/?cid=stumble', expStatus:200, expUrl:'/en/', reqNotes:'stet'},
    {reqUrl:'/reactivate33', expStatus:200, expUrl:'/en/reactivation/', reqNotes:''},
    {reqUrl:'/prospect', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/youtube', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/samplepromotion', expStatus:200, expUrl:'/en/newsstand/', reqNotes:''},
    {reqUrl:'/youtube_fr', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/reactivation33/', expStatus:200, expUrl:'/fr/reactivation-fr/', reqNotes:''},
    {reqUrl:'/30days', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30DAYS', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free11', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freecbu', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freeche', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freeflr', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freehlo', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freelou', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freelue', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freemme', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freespo', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freetdp', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/60DAYS', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/60Days', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/60days', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/680', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/680news', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmiles914', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmiles9141', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/alerts', expStatus:200, expUrl:'/', reqNotes:'stet'},
    {reqUrl:'/airmiles9142', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/AirmilesGreen', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmilesgreen', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/AirmilesPurple', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmilespurple', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmilesshops', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/AMemployee', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/amemployee', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/android', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/android/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/android/?fromReader=true', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/android?fromReader=true', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/appads3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffer1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffer2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffer3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffernow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/aprilspecial', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/EM101813windows', expStatus:200, expUrl:'http://apps.microsoft.com/windows/en-ca/app/next-issue-unlimited-magazines/7d3fc73f-7a3e-44d1-8264-e435e0c0d115', reqNotes:'XCROSS SITE'},
    {reqUrl:'/bam9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bloggers', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption/?utm_medium=social&utm_source=nextissue&utm_campaign=2014_8&utm_content=bloggeroutreach_rcode-3months&utm_term=ni_bloggeroutreach&cid=ni_bloggeroutreach', reqNotes:'XCROSS SITE'},
    {reqUrl:'/BAM9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/boobyball', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/banquescotia', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/baseball', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/easypay', expStatus:200, expUrl:'http://easypay.nextissue.ca', reqNotes:'XCROSS SITE'},
    {reqUrl:'/baseball/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bcmagazine', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bellmedia_0415', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/blogger', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bonus30', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bundling', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bundling-offer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bus_0415', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/paiementpratique', expStatus:200, expUrl:'http://easypay.nextissue.ca/fr/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/buytopia2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/ignite', expStatus:200, expUrl:'http://ignite.msdg.ca/?ran=', reqNotes:'XCROSS SITE'},
    {reqUrl:'/buytopia3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia5', expStatus:200, expUrl:'/en/', reqNotes:''}    
];

let A2 = [
    {reqUrl:'/buytopia6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/canada_0415', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/codepromo', expStatus:200, expUrl:'https://secure.texture.ca/redemption?lang=fr', reqNotes:'XCROSS SITE'},
    {reqUrl:'/codepromoRFR', expStatus:200, expUrl:'https://secure.nextissue.ca/redemption?lang=fr&?utm_medium=other&utm_source=RFR&utm_campaign=2015_4&utm_content=90day&utm_term=RFR_90day_042715&cid=RFR_90day_042715', reqNotes:'XCROSS SITE'},
    {reqUrl:'/codepromorfr', expStatus:200, expUrl:'https://secure.texture.ca/redemption?lang=fr&?utm_medium=other&utm_source=RFR&utm_campaign=2015_4&utm_content=90day&utm_term=RFR_90day_042715&cid=RFR_90day_042715', reqNotes:'XCROSS SITE'},
    {reqUrl:'/canadianbusiness2014', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/contact', expStatus:200, expUrl:'http://support.nextissue.ca/Tickets/Submit/RenderForm/1', reqNotes:'XCROSS SITE'},
    {reqUrl:'/elan3ans', expStatus:200, expUrl:'http://ignite3y.nextissue.msdg.ca/fr', reqNotes:'XCROSS SITE'},
    {reqUrl:'/card-tjx', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/care2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/care2/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/cdnbusinesssubscribe', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/chatelaine2014', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/ChatelaineSeptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/dinnerxdesign', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption?utm_medium=email&utm_source=dinnerxdesign&utm_campaign=2015_1&utm_content=90day&utm_term=dinnerxdesign_90day_012915&cid=dinnerxdesign_90day_012915', reqNotes:'XCROSS SITE'},
    {reqUrl:'/chatelaineseptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/ignite3years', expStatus:200, expUrl:'http://ignite3y.texture.msdg.ca', reqNotes:'XCROSS SITE'},
    {reqUrl:'/chatelainesubscribe', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/desjardinsmembers', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/diabolica', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/ignite90days', expStatus:200, expUrl:'http://ignite90d.nextissue.msdg.ca', reqNotes:'XCROSS SITE'},
    {reqUrl:'/elan90jours', expStatus:200, expUrl:'http://ignite90d.nextissue.msdg.ca/fr', reqNotes:'XCROSS SITE'},
    {reqUrl:'/samsung90offer', expStatus:200, expUrl:'http://samsung.texture.msdg.ca/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/samsungoffre90', expStatus:200, expUrl:'http://samsung.texture.msdg.ca/fr', reqNotes:'XCROSS SITE'},
    {reqUrl:'/samsung90offerS2', expStatus:200, expUrl:'http://samsungs2.texture.msdg.ca/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/samsungoffre90S2', expStatus:200, expUrl:'http://samsungs2.texture.msdg.ca/fr', reqNotes:'XCROSS SITE'},
    {reqUrl:'/direct', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/echoage', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/ECHOAGE', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/ECHOage', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/evenements', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/events', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fashionshow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fashionweek', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/flare2014', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/flareparty', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/flarebox', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/FlareSeptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/flareseptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/flaresubscribe', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/flarexheys', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/flightcenter', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/forgotpassword', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/auth/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/forgotpassword', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/auth/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/flightcentre', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/free', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/free30', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/free30np', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/freecharger', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/freeoffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/freetrial', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/freetrial', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/freetrial', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/freetrial', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/freetry', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/getapriloffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/gateway', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption/?cid=gateway', reqNotes:'XCROSS SITE'},
    {reqUrl:'/getapriloffernow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/getit', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/getnow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/getnow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/getoffernow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/getrightnow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/groupon', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/giftforyou', expStatus:200, expUrl:'https://secure.nextissue.ca/redemption/?utm_medium=dm&utm_source=MtnCble&utm_campaign=2015_5&utm_content=90day&utm_term=mtncbl_90day_052015_dm&cid=mtncbl_90day_052015_dm', reqNotes:'XCROSS SITE'},
    {reqUrl:'/hello2014', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/helloparty', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/HelloSeptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/helloseptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/hellosubscribe', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/holidayoffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/holidayoffer1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/holidayoffer2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/holidayoffer3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/homeshow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/IAAP', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/HomeIce', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/HOMEICE', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/homeice', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/contact', expStatus:200, expUrl:'http://support.nextissue.ca/Tickets/Submit/RenderForm/1', reqNotes:'XCROSS SITE'},
    {reqUrl:'/iaap', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/jackfm', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/julyrogers', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/support/', expStatus:200, expUrl:'http://support.texture.ca/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/kinderbueno', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/klout', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive11', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/kognitive9', expStatus:200, expUrl:'/en/', reqNotes:''}    
];
let A3 = [
    {reqUrl:'/launchoffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/launchoffer1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/launchoffer2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/launchoffer3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/launchoffer4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/launchoffer5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/launchoffer6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/leafs', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/lipton', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/livenation_0415', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/longos', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/loulou2014', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/loulousubscribe', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/macleans2014', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/MacleansSeptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/macleansseptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/macleanssubscribe', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mall', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/marilyndenis_0415', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mayflyer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mcgillalum', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mcgillalumni0615', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/membresdesjardins', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/metro', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/millesaeroplan', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/modernmama', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/moneysensesubscribe', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaic', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaic1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaiccard', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall11', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall12', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall13', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall14', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall15', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall16', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall17', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall18', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall19', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall20', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mosaicmall9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/movieent', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/mrlube', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/my30days', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/newcharger', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/novoffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/novoffer1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/novoffer2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/octoffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/octoffer1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/octoffer2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offer1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offer10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offer2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offer3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offer4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offer5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offer7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offer8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offer9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offerjuly', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/northernradio', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption/?utm_medium=social&utm_source=northernradio&utm_campaign=2014_8&utm_content=northernradiogiveaway_rcode-3months&utm_term=northernradio_giveaway&cid=northernradio_giveaway', reqNotes:'XCROSS SITE'},
    {reqUrl:'/offerlaunch1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offerlaunch2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offerlaunch3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offerlaunch4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offerlaunch5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offerlaunch6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offream', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/offresuper/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/p1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p11', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p12', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p13', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p14', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p15', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p16', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p17', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p18', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p19', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p20', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p21', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p22', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p23', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p24', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/offrezcadeau', expStatus:200, expUrl:'https://secure.indas.on.ca/rogers/promo/staff/fr/OffrezCadeau/?utm_medium=gifts&utm_source=texture&utm_campaign=2015_11&utm_content=gifting&utm_term=empgifts_1124215_fr&cid=empgifts_1124215_fr', reqNotes:'XCROSS SITE'},
    {reqUrl:'/ompbasic', expStatus:200, expUrl:'https://secure.chatelaine.com/servlet/OrdersGateway?cds_mag_code=CHE&cds_page_id=178225', reqNotes:'XCROSS SITE'},
    {reqUrl:'/omppremium', expStatus:200, expUrl:'https://secure.chatelaine.com/servlet/OrdersGateway?cds_mag_code=CHE&cds_page_id=196190', reqNotes:'XCROSS SITE'},
    {reqUrl:'/p25', expStatus:200, expUrl:'/en/', reqNotes:''}    
];
let A4 = [
    {reqUrl:'/p26', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p27', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p28', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p29', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p30', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p31', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p32', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p33', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p34', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p35', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p36', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p37', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p38', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p39', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p40', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P40', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p41', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P41', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p42', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P42', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p43', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P43', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p44', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P44', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p45', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P45', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p46', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P46', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p47', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P47', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p48', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P48', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p49', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P49', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p50', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P50', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p51', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P51', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p52', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P52', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p53', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P53', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p54', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P54', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p55', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P55', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p56', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P56', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p57', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P57', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p58', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P58', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p59', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P59', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p60', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P60', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p61', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P61', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p62', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P62', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p63', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P63', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p64', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P64', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p65', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P65', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p66', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P66', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p67', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P67', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p68', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P68', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p69', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P69', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p70', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P70', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p71', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P71', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p72', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P72', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p73', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P73', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p74', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P74', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p75', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P75', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p76', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P76', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p77', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P77', expStatus:200, expUrl:'/en/', reqNotes:''}
    
];
let A5 = [
    {reqUrl:'/p78', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P78', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p79', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P79', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p80', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P80', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p81', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P81', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p82', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P82', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p83', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P83', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p84', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P84', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p85', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P85', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/P9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/p9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/pearsonbonus', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/PearsonBonus', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/Perkopolis', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/perkopolis', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/powerplant', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/POWERPLANT', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/Powerplant', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/PowerPlant', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/prepaid', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/primedemai', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/primekinderbueno', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/raptors', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rcicable', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rciwireless', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/redflagoffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rediscover', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/referafriend', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/referyourfriends', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogers04', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogers05', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogers2014', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogers914', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogers9141', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogers9142', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogersbill', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogerscupmontreal', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogerscuptoronto', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogersjuly', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogersnc', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/RogersNC', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/ROGERSNC', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogersNC', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/roots', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rra', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/samstub', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/scenepumped1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/redeem', expStatus:200, expUrl:'https://secure.texture.ca/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/scenepumped2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/scenepumped3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/scenepumped4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/scenepumped5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/schooloffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rfrredemption', expStatus:200, expUrl:'https://secure.nextissue.ca/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/RFRredemption', expStatus:200, expUrl:'https://secure.nextissue.ca/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/scotiabank', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/screwit', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/SeptemberCBU', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/septembercbu', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/SeptemberChatelaine', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/septemberchatelaine', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/SeptemberLOULOU', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/septemberloulou', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/SeptemberTDP', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/septembertdp', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/shopperbonus', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/rogersloyaltyoffer', expStatus:200, expUrl:'https://secure.indas.on.ca/rogers/next/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/shopperstrial', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/shoppertrial', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/signupnow1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/signupnow2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/signupnow3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/signupnow4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/signupnow5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/signupnow6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/signupnow7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/signupnow8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/smutsoiree', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/sourcegift', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/sportsnet2014', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/samsungtabafr?utm_medium=partnership&utm_source=Samsung&utm_campaign=2015_4&utm_content=30days&utm_term=SamsungTabAofferFR_042015&cid=SamsungTabAofferFR_042015', expStatus:200, expUrl:'https://secure.nextissue.ca/redemption?lang=fr', reqNotes:'XCROSS SITE'},
    {reqUrl:'/SportsnetSeptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/sportsnetseptember', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/sportsnetsubscribe', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/startmy30', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/students', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/summer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/targetsource', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/teambuy', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tedxtoronto', expStatus:200, expUrl:'/en/', reqNotes:''}    
];
let A6 = [
    {reqUrl:'/tedxvancouver', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/test', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/test1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/todaysparent2014', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/todaysparentsubscribe', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/trade', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/travelzoo', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tryfree', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tsc', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tsc01', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tsc02', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tsc03', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tsc04', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tschp', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tscnew', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tsn_0415', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tuango', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tuangobonus', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv11', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv12', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv13', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/specialoffer', expStatus:200, expUrl:'https://secure.texture.ca/signin?cid=pricelinedis_0316&utm_medium=dig&utm_source=texture&utm_campaign=2016_3&utm_content=pricelinedis&utm_term=pricelinedis_0316&offer_type=price_line_discount', reqNotes:'XCROSS SITE'},
    {reqUrl:'/tv14', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv15', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv16', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv17', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv18', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv19', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv20', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv21', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv22', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv23', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/staffgift', expStatus:200, expUrl:'https://gift.texture.ca/staff/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/tv5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/teddybearaffair', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/tv8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tv9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/tweetpromo', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/twitterdeal', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/twitteroffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/twitterpromo', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/ubc', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/unialum', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/uoftalumni0615', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/usask', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/uvic', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/staffgifts', expStatus:200, expUrl:'https://gift.texture.ca/staff/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/welcomeback', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/windows8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/wineoclock', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/wnetwork_0415', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/woodbine', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/yorkalum', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/yorkalumni0615', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/zoomershow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/EM101813ipad', expStatus:200, expUrl:'https://itunes.apple.com/ca/app/rogers-next-issue/id649174756?ls=1&mt=8', reqNotes:'XCROSS SITE'},
    {reqUrl:'/ribfest', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/readersdigest', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/fword', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/cibc', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/collector', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/evernote', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/CU', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/cu', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/coupon', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/redemption', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/new', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/cu2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/LOULOU', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/loulou', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/endo', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/schoolfinder', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/julyoffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/youroffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/specialapril', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/maybonus', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/hotdocs', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/via', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/mastercard', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/win8', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/torontolife', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/theshoppingchannel', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/EM101813ipad', expStatus:200, expUrl:'https://itunes.apple.com/ca/app/rogers-next-issue/id649174756?ls=1&mt=8', reqNotes:'XCROSS SITE'},
    {reqUrl:'/EM101813android', expStatus:200, expUrl:'https://play.google.com/store/apps/details?id=com.nim.rogers', reqNotes:'XCROSS SITE'},
    {reqUrl:'/metrogifts', expStatus:200, expUrl:'https://w1.buysub.com/servlet/OrdersGateway?cds_mag_code=CHE&cds_page_id=170973', reqNotes:'XCROSS SITE'},
    {reqUrl:'/stargifts', expStatus:200, expUrl:'https://w1.buysub.com/servlet/OrdersGateway?cds_mag_code=CHE&cds_page_id=170973', reqNotes:'XCROSS SITE'},
    {reqUrl:'/ottawamag', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/natgeo', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/financialpost', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/thirty', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/THIRTY', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/variety', expStatus:200, expUrl:'https://secure.texture.ca/redemption?utm_medium=ptnshps&utm_source=varietyclub&utm_campaign=2015_11&utm_content=30days&utm_term=varclubtlthn_112415&cid=varclubtlthn_112415', reqNotes:'XCROSS SITE'}
];
let A7 = [
    {reqUrl:'/varietyclub', expStatus:200, expUrl:'https://secure.texture.ca/redemption?utm_medium=ptnshps&utm_source=varietyclub&utm_campaign=2015_11&utm_content=30days&utm_term=varclubtlthn_112415&cid=varclubtlthn_112415', reqNotes:'XCROSS SITE'},
    {reqUrl:'/startnextisue', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/vip', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption/?utm_medium=experiential&utm_source=rogers_tifflounge&utm_campaign=2014_9&utm_content=code_90days&utm_term=tiff_lounge&cid=tiff_lounge', reqNotes:'XCROSS SITE'},
    {reqUrl:'/vivaitalia', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/startoffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/introdeal', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/special', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/intro', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/signmeup', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/start', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/signup', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/startnow', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/nowstart', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/hohoto', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/keepitcoming', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/keepitcoming', expStatus:200, expUrl:'/', reqNotes:''},
    {reqUrl:'/tabrog', expStatus:200, expUrl:'/', reqNotes:''}    
];

//let redirectList = [ ...A2, ...A3, ...A4, ...A5, ...A6, ...A7 ];
//let redirectList = [ ...DONOTREDIRECT_array,...TAXONOMY_ARRAY, ...A1, ...A2, ...A3, ...A4, ...A5, ...A6 ];
let redirectList = [ ...DONOTREDIRECT_array, ...TAXONOMY_ARRAY, ...STILLFAILING_array ];
