const DONOTREDIRECT_array = [
    {reqUrl:'/en/', expStatus:200, expUrl:'/en/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/', expStatus:200, expUrl:'/fr/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/newsstand/', expStatus:200, expUrl:'/en/newsstand/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/kiosque/', expStatus:200, expUrl:'/fr/kiosque/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/pricing/', expStatus:200, expUrl:'/en/pricing/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/newsstand/', expStatus:200, expUrl:'/en/newsstand/', reqNotes:'MUST NOT REDIRECT, possible pll_language cookie issue'},
    {reqUrl:'/en/features/', expStatus:200, expUrl:'/en/features/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/about-us/contact-us/', expStatus:200, expUrl:'/en/about-us/contact-us/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/device-ipad/', expStatus:200, expUrl:'/en/device-ipad/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/device-android/', expStatus:200, expUrl:'/en/device-android/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/device-kindle-fire/', expStatus:200, expUrl:'/en/device-kindle-fire/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/terms-of-service/', expStatus:200, expUrl:'/en/legal/terms-of-service/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/copyright-policy/', expStatus:200, expUrl:'/en/legal/copyright-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/privacy-policy/', expStatus:200, expUrl:'/en/legal/privacy-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/inapp-terms-of-service/', expStatus:200, expUrl:'/en/legal/inapp-terms-of-service/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/inapp-copyright-policy/', expStatus:200, expUrl:'/en/legal/inapp-copyright-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/inapp-rogers-copyright-policy/', expStatus:200, expUrl:'/en/legal/inapp-rogers-copyright-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/legal/inapp-privacy-policy/', expStatus:200, expUrl:'/en/legal/inapp-privacy-policy/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/tarification/', expStatus:200, expUrl:'/fr/tarification/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/kiosque/', expStatus:200, expUrl:'/fr/kiosque/', reqNotes:'MUST NOT REDIRECT, possible pll_language cookie issue'},
    {reqUrl:'/fr/fonctionnalites/', expStatus:200, expUrl:'/fr/fonctionnalites/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/a-propos-de-nous/contactez-nous/', expStatus:200, expUrl:'/fr/a-propos-de-nous/contactez-nous/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/ipad-et-iphone/', expStatus:200, expUrl:'/fr/ipad-et-iphone/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/device-android-fr/', expStatus:200, expUrl:'/fr/device-android-fr/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/kindle-fire/', expStatus:200, expUrl:'/fr/kindle-fire/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/conditions-dutilisation/', expStatus:200, expUrl:'/fr/politiques/conditions-dutilisation/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/inapp-conditions-dutilisation/', expStatus:200, expUrl:'/fr/politiques/inapp-conditions-dutilisation/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/inapp-droit-dauteur/', expStatus:200, expUrl:'/fr/politiques/inapp-droit-dauteur/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/inapp-politique-canadienne-sur-le-droit-dauteur/', expStatus:200, expUrl:'/fr/politiques/inapp-politique-canadienne-sur-le-droit-dauteur/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/inapp-confidentialite/', expStatus:200, expUrl:'/fr/politiques/inapp-confidentialite/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/droit-dauteur/', expStatus:200, expUrl:'/fr/politiques/droit-dauteur/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/politiques/confidentialite/', expStatus:200, expUrl:'/fr/politiques/confidentialite/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/support-fr/', expStatus:200, expUrl:'https://support.texture.ca/fr/', reqNotes:'DO NOT CHANGE, CORS'},
    {reqUrl:'/en/support/', expStatus:200, expUrl:'https://support.texture.ca/en/', reqNotes:'DO NOT CHANGE, CORS'},
    {reqUrl:'/blog', expStatus:200, expUrl:'/en/blog/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/en/blog', expStatus:200, expUrl:'/en/blog/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/en/blog/', expStatus:200, expUrl:'/en/blog/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/blogue', expStatus:200, expUrl:'/fr/blogue/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/blogue/', expStatus:200, expUrl:'/fr/blogue/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/fr/blogue', expStatus:200, expUrl:'/fr/blogue/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/fr/blogue/', expStatus:200, expUrl:'/fr/blogue/', reqNotes:'MUST NOT REDIRECT - site goes in a redirect loop'},
    {reqUrl:'/en/dl/category/9000000000041/', expStatus:200, expUrl:'/en/dl/category/9000000000041/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/dl/view/highlights/', expStatus:200, expUrl:'/en/dl/view/highlights/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/fr/magazines/ebony-fr/', expStatus:200, expUrl:'/fr/magazines/ebony-fr/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/magazines/ebony/', expStatus:200, expUrl:'/en/magazines/ebony/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/canadian-favourites-magazines/', expStatus:200, expUrl:'/en/canadian-favourites-magazines/', reqNotes:'Could this redirect?'},
    {reqUrl:'/en/2017/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/2009/12/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/2009/whateverafter', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/2016/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/2005/08/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/2012/whateverafter', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/en/tag', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/tag/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/tag/whatever-you-put-after', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/tag', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/tag/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/tag/whatever-you-put-after', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/en/article', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/article/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/en/article/whatever-you-put-after', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/article', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/article/', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/article/whatever-you-put-after', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/en/?nimportalpartner=delta-airlines', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/fr/?nimportalpartner=delta-airlines-fr', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/magazines/ebony-fr/', expStatus:200, expUrl:'/fr/magazines/ebony-fr/', reqNotes:'MUST NOT REDIRECT'},
    {reqUrl:'/en/magazines/ebony/', expStatus:200, expUrl:'/en/magazines/ebony/', reqNotes:'MUST NOT REDIRECT'}
];


const TAXONOMY_ARRAY = [
{reqUrl:'/en/canadian-favourites-magazines/', expStatus:200, expUrl:'/en/canadian-favourites-magazines/', reqNotes:'Could this redirect?'},
{reqUrl:'/en/2017/', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/en/2009/12/', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/en/2009/whateverafter', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/fr/2016/', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/fr/2005/08/', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/fr/2012/whateverafter', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/en/tag', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/en/tag/', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/en/tag/whatever-you-put-after', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/fr/tag', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/fr/tag/', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/fr/tag/whatever-you-put-after', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/en/article', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/en/article/', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/en/article/whatever-you-put-after', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/fr/article', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/fr/article/', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/fr/article/whatever-you-put-after', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/en/?nimportalpartner=delta-airlines', expStatus:200, expUrl:'/en/', reqNotes:''},
{reqUrl:'/fr/?nimportalpartner=delta-airlines-fr', expStatus:200, expUrl:'/fr/', reqNotes:''},
{reqUrl:'/fr/magazines/ebony-fr/', expStatus:200, expUrl:'/fr/magazines/ebony-fr/', reqNotes:'MUST NOT REDIRECT'},
{reqUrl:'/en/magazines/ebony/', expStatus:200, expUrl:'/en/magazines/ebony/', reqNotes:'MUST NOT REDIRECT'},
];

let A1 = [
    {reqUrl:'/?cid=stumble', expStatus:200, expUrl:'/en/', reqNotes:'stet'},
    {reqUrl:'/reactivate33', expStatus:200, expUrl:'/en/reactivation/', reqNotes:''},
    {reqUrl:'/prospect', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/youtube', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/samplepromotion', expStatus:200, expUrl:'/en/newsstand/', reqNotes:''},
    {reqUrl:'/youtube_fr', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/fr/reactivation33/', expStatus:200, expUrl:'/fr/reactivation-fr/', reqNotes:''},
    {reqUrl:'/30days', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30DAYS', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free11', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30free9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freecbu', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freeche', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freeflr', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freehlo', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freelou', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freelue', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freemme', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freespo', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/30freetdp', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/60DAYS', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/60Days', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/60days', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/680', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/680news', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmiles914', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmiles9141', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/alerts', expStatus:200, expUrl:'/?cid=alerts', reqNotes:'stet'},
    {reqUrl:'/airmiles9142', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/AirmilesGreen', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmilesgreen', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/AirmilesPurple', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmilespurple', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/airmilesshops', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/AMemployee', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/amemployee', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/android', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/android/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/android/?fromReader=true', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/android?fromReader=true', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/appads3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffer1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffer2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffer3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/apriloffernow', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/aprilspecial', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM6', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM7', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bam8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/BAM8', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/EM101813windows', expStatus:200, expUrl:'http://apps.microsoft.com/windows/en-ca/app/next-issue-unlimited-magazines/7d3fc73f-7a3e-44d1-8264-e435e0c0d115', reqNotes:'XCROSS SITE'},
    {reqUrl:'/bam9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bloggers', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption/?utm_medium=social&utm_source=nextissue&utm_campaign=2014_8&utm_content=bloggeroutreach_rcode-3months&utm_term=ni_bloggeroutreach&cid=ni_bloggeroutreach', reqNotes:'XCROSS SITE'},
    {reqUrl:'/BAM9', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/boobyball', expStatus:200, expUrl:'https://secure.nextissue.ca/secure/common/redemption', reqNotes:'XCROSS SITE'},
    {reqUrl:'/banquescotia', expStatus:200, expUrl:'/fr/', reqNotes:''},
    {reqUrl:'/baseball', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/easypay', expStatus:200, expUrl:'http://easypay.nextissue.ca', reqNotes:'XCROSS SITE'},
    {reqUrl:'/baseball/', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bcmagazine', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bellmedia_0415', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/blogger', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bonus30', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bundling', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bundling-offer', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/bus_0415', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia1', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia10', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/paiementpratique', expStatus:200, expUrl:'http://easypay.nextissue.ca/fr/', reqNotes:'XCROSS SITE'},
    {reqUrl:'/buytopia2', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/ignite', expStatus:200, expUrl:'http://ignite.msdg.ca/?ran=', reqNotes:'XCROSS SITE'},
    {reqUrl:'/buytopia3', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia4', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia5', expStatus:200, expUrl:'/en/', reqNotes:''},
    {reqUrl:'/buytopia6', expStatus:200, expUrl:'/en/', reqNotes:''}    
];

let A2 = [];
let A3 = [];
let A4 = [];
let A5 = [];
let A6 = [];

let redirectList = [ ...DONOTREDIRECT_array,...TAXONOMY_ARRAY, ...A1, /* ...A2, ...A3, ...A4, ...A5, ...A6 */ ];
